version: '3.8'

services:
  db:
    image: mysql:9.3
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gimnasio
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_USER=root
      - DB_PASS=root
      - DB_HOST=db
      - DB_PORT=3306
      - DB_SCHEMA=gimnasio
      - APP_HOST=0.0.0.0
      - APP_PORT=8080
      - JWT_SECRET='d6d6c772219f3b65cc8254983632c930f6197c54b3a8de71e31689d839a386b4'
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: