services:
  mongo:
    image: mongo:7.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB:-demo}
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d:ro
      - mongo_data:/data/db
  memcached:
    image: memcached:1.6-alpine
    restart: unless-stopped
    command: ["-m", "64"]
    ports:
      - "11211:11211"
volumes:
  mongo_data:
